---
- hosts: web
  become: yes
  become_method: sudo
  tasks:
   - name: create group "devops" to web server
     group:
       name: Devops
       state: present
       gid: 2021

   - name: create a user
     user:
       name: Nerisha
       group: Devops
       password: ydXROTSI9iVek
       shell: "/bin/bash"
